/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Christian
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jdptelas = new javax.swing.JDesktopPane();
        lblDestop = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        jCadastrar = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmClientes = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmVeiculos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JFunc = new javax.swing.JMenu();
        jbfuncionarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmSair = new javax.swing.JMenuItem();
        jMoviment = new javax.swing.JMenu();
        jmlocacao = new javax.swing.JMenu();
        jbLocacao = new javax.swing.JMenuItem();
        jmCancelamento = new javax.swing.JMenuItem();
        jmFechamento = new javax.swing.JMenu();
        jmFecLocacao = new javax.swing.JMenuItem();
        jjRelatorios = new javax.swing.JMenu();
        jmRelVeiculos = new javax.swing.JMenuItem();
        jmComprov = new javax.swing.JMenuItem();
        jmRelFachamentos = new javax.swing.JMenuItem();
        jmRelClientes = new javax.swing.JMenuItem();
        jSobre = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("TelaPrincipal"); // NOI18N

        jdptelas.setLayer(lblDestop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdptelasLayout = new javax.swing.GroupLayout(jdptelas);
        jdptelas.setLayout(jdptelasLayout);
        jdptelasLayout.setHorizontalGroup(
            jdptelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDestop, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        jdptelasLayout.setVerticalGroup(
            jdptelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdptelasLayout.createSequentialGroup()
                .addComponent(lblDestop, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jCadastrar.setText("Cadastrar");
        jCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCadastrar.setFocusable(false);
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });
        jCadastrar.add(jSeparator3);

        jmClientes.setText("Clientes");
        jmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClientesActionPerformed(evt);
            }
        });
        jCadastrar.add(jmClientes);
        jCadastrar.add(jSeparator4);

        jmVeiculos.setText("Veiculos");
        jmVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVeiculosActionPerformed(evt);
            }
        });
        jCadastrar.add(jmVeiculos);
        jCadastrar.add(jSeparator1);

        JFunc.setText("Funcionarios");

        jbfuncionarios.setText("Funcionarios");
        jbfuncionarios.setActionCommand("funcionarios");
        jbfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfuncionariosActionPerformed(evt);
            }
        });
        JFunc.add(jbfuncionarios);

        jCadastrar.add(JFunc);
        jCadastrar.add(jSeparator2);

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jCadastrar.add(jmSair);

        MenuPrincipal.add(jCadastrar);

        jMoviment.setText("Movimentações");

        jmlocacao.setText("Locação");
        jmlocacao.setActionCommand("Locacao");

        jbLocacao.setText("Inclusão");
        jbLocacao.setActionCommand("Inclusao");
        jbLocacao.setBorderPainted(true);
        jbLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLocacaoActionPerformed(evt);
            }
        });
        jmlocacao.add(jbLocacao);

        jmCancelamento.setText("Cancelamento");
        jmCancelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCancelamentoActionPerformed(evt);
            }
        });
        jmlocacao.add(jmCancelamento);

        jMoviment.add(jmlocacao);

        jmFechamento.setText("Fechamentos");

        jmFecLocacao.setText("Fechamento locação");
        jmFecLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFecLocacaoActionPerformed(evt);
            }
        });
        jmFechamento.add(jmFecLocacao);

        jMoviment.add(jmFechamento);

        MenuPrincipal.add(jMoviment);

        jjRelatorios.setText("Relatórios");

        jmRelVeiculos.setText("Relatórios Veiculos");
        jjRelatorios.add(jmRelVeiculos);

        jmComprov.setText("Comprovantes");
        jjRelatorios.add(jmComprov);

        jmRelFachamentos.setText("Relatorio Fechamentos");
        jjRelatorios.add(jmRelFachamentos);

        jmRelClientes.setText("Relatorios Clientes");
        jjRelatorios.add(jmRelClientes);

        MenuPrincipal.add(jjRelatorios);

        jSobre.setText("Sobre");
        MenuPrincipal.add(jSobre);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdptelas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdptelas)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfuncionariosActionPerformed
        jiCaFuncionarios cfu = new jiCaFuncionarios();
        lblDestop.add(cfu);
        cfu.show();
    }//GEN-LAST:event_jbfuncionariosActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmCancelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCancelamentoActionPerformed
        jiCancLocacao ccl = new jiCancLocacao();
        lblDestop.add(ccl);
        ccl.show();
    }//GEN-LAST:event_jmCancelamentoActionPerformed

    private void jmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClientesActionPerformed
        jiCaCliente cli = new jiCaCliente();
        lblDestop.add(cli);
        cli.show();
    }//GEN-LAST:event_jmClientesActionPerformed

    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jCadastrarActionPerformed

    private void jmVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVeiculosActionPerformed
        jiCaVeiculos cve = new jiCaVeiculos();
        lblDestop.add(cve);
        cve.show();
    }//GEN-LAST:event_jmVeiculosActionPerformed

    private void jbLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLocacaoActionPerformed
        jiCaLocacao clo = new jiCaLocacao();
        lblDestop.add(clo);
        clo.show();
    }//GEN-LAST:event_jbLocacaoActionPerformed

    private void jmFecLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFecLocacaoActionPerformed
        jiFecLocacao cfo = new jiFecLocacao();
        lblDestop.add(cfo);
        cfo.show();
    }//GEN-LAST:event_jmFecLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JFunc;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu jCadastrar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMoviment;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu jSobre;
    private javax.swing.JMenuItem jbLocacao;
    private javax.swing.JMenuItem jbfuncionarios;
    private javax.swing.JDesktopPane jdptelas;
    private javax.swing.JMenu jjRelatorios;
    private javax.swing.JMenuItem jmCancelamento;
    private javax.swing.JMenuItem jmClientes;
    private javax.swing.JMenuItem jmComprov;
    private javax.swing.JMenuItem jmFecLocacao;
    private javax.swing.JMenu jmFechamento;
    private javax.swing.JMenuItem jmRelClientes;
    private javax.swing.JMenuItem jmRelFachamentos;
    private javax.swing.JMenuItem jmRelVeiculos;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenuItem jmVeiculos;
    private javax.swing.JMenu jmlocacao;
    private javax.swing.JLabel lblDestop;
    // End of variables declaration//GEN-END:variables
}
